FROM python:3.12-slim

WORKDIR /app

# Install pinned dependencies first for layer caching and reproducible builds. The lock
# is generated by `make lock`; regenerate it when requirements.txt changes.
COPY requirements.lock ./
RUN pip install --no-cache-dir -r requirements.lock

COPY . .
RUN pip install --no-cache-dir --no-deps .

CMD ["python", "-m", "argus.ingest.flows"]
